"""Defines the top-level xax API.

This package is structured so that all the important stuff can be accessed
without having to dig around through the internals. This is done by lazily
importing the module by name.

This file can be maintained by updating the imports at the bottom of the file
and running the update script:

.. code-block:: bash

    python -m scripts.update_api --inplace
"""

__version__ = "0.4.7"

# This list shouldn't be modified by hand; instead, run the update script.
__all__ = [
    "AttentionCache",
    "CrossAttentionBlock",
    "Fp8ScalesCache",
    "RMSNorm",
    "RotaryEmbedding",
    "SelfAttentionBlock",
    "SwiGLU",
    "Transformer",
    "TransformerBlock",
    "TransformerBlockCache",
    "TransformerCache",
    "TransformerStack",
    "apply_linear",
    "can_use_cudnn_attention",
    "BaseODESolver",
    "ConsistencyModel",
    "EulerODESolver",
    "GaussianDiffusion",
    "HeunODESolver",
    "RK4ODESolver",
    "cast_beta_schedule",
    "cast_diffusion_loss_fn",
    "cast_diffusion_pred_mode",
    "cast_ode_solver_type",
    "get_diffusion_beta_schedule",
    "get_ode_solver",
    "LLM",
    "LLMConfig",
    "LLMRepo",
    "build_pretrained_model",
    "chunked_cross_entropy_acc",
    "chunked_cross_entropy_loss",
    "hf_config_to_llm_config",
    "llm_generate",
    "llm_generate_jit",
    "load_hf_config",
    "load_hf_weights_into_llm",
    "tie_embedding_and_head",
    "BaseSSMBlock",
    "DiagSSMBlock",
    "SSM",
    "SSMBlock",
    "UNet",
    "UserConfig",
    "field",
    "get_data_dir",
    "get_pretrained_models_dir",
    "get_run_dir",
    "load_user_config",
    "State",
    "cast_step_kind",
    "cast_activation_type",
    "get_activation",
    "Categorical",
    "MixtureOfGaussians",
    "Normal",
    "ProbabilityDistribution",
    "FourierEmbeddings",
    "IdentityPositionalEmbeddings",
    "LearnedPositionalEmbeddings",
    "RotaryEmbeddings",
    "SinusoidalEmbeddings",
    "apply_rotary_embeddings",
    "cast_embedding_kind",
    "fourier_embeddings",
    "get_positional_embeddings",
    "get_rotary_embeddings",
    "rotary_embeddings",
    "cubic_bezier_interpolation",
    "euler_to_quat",
    "get_projected_gravity_vector_from_quat",
    "normalize",
    "quat_mul",
    "quat_to_euler",
    "quat_to_rotmat",
    "quat_to_yaw",
    "rotate_vector_by_quat",
    "rotation6d_to_rotation_matrix",
    "rotation_matrix_to_quat",
    "rotation_matrix_to_rotation6d",
    "LoRALinear",
    "apply_lora_and_merge",
    "extract_lora_weights",
    "load_lora_weights",
    "lora_filter_spec",
    "loraize",
    "loraize_by_path",
    "loraize_linear",
    "merge_lora",
    "cast_euclidean_norm_type",
    "dynamic_time_warping",
    "get_euclidean_norm",
    "cast_norm_type",
    "get_norm_1d",
    "get_norm_2d",
    "get_norm_3d",
    "get_norm_linear",
    "is_master",
    "BaseLauncher",
    "CliLauncher",
    "MultiCpuLauncher",
    "MultiDeviceLauncher",
    "SingleDeviceLauncher",
    "Distribution",
    "Histogram",
    "Image",
    "Images",
    "LabeledImages",
    "LogDistribution",
    "LogError",
    "LogErrorSummary",
    "LogGraph",
    "LogHistogram",
    "LogImage",
    "LogLine",
    "LogMesh",
    "LogPing",
    "LogScalar",
    "LogStatus",
    "LogVideo",
    "Logger",
    "LoggerImpl",
    "Mesh",
    "Scalar",
    "Tokens",
    "Video",
    "CallbackLogger",
    "JsonLogger",
    "StateLogger",
    "StdoutLogger",
    "TensorboardLogger",
    "load_ckpt",
    "CPUStatsOptions",
    "DataloadersConfig",
    "DataloadersMixin",
    "GPUStatsOptions",
    "ParallelConfig",
    "ParallelMixin",
    "StepContext",
    "InitParams",
    "Script",
    "ScriptConfig",
    "Config",
    "SupervisedConfig",
    "SupervisedTask",
    "Task",
    "collate",
    "collate_non_null",
    "breakpoint_if_nonfinite",
    "get_named_leaves",
    "log_if_nonfinite",
    "BaseFileDownloader",
    "ContextTimer",
    "CumulativeTimer",
    "DataDownloader",
    "IntervalTicker",
    "IterationTimer",
    "ModelDownloader",
    "NaNError",
    "StateTimer",
    "check_md5",
    "check_sha256",
    "cpu_count",
    "date_str",
    "diff_configs",
    "get_git_state",
    "get_random_port",
    "get_state_dict_prefix",
    "get_training_code",
    "save_config",
    "stage_environment",
    "to_markdown_table",
    "grad",
    "jit",
    "scan",
    "to_numpy",
    "to_scalar",
    "vmap",
    "save_jaxpr_dot",
    "ColoredFormatter",
    "configure_logging",
    "one_hot",
    "partial_flatten",
    "worker_chunk",
    "profile",
    "compute_nan_ratio",
    "diff_pytree",
    "flatten_array",
    "flatten_pytree",
    "get_pytree_mapping",
    "get_pytree_param_count",
    "pytree_has_nans",
    "reshuffle_pytree",
    "reshuffle_pytree_along_dims",
    "reshuffle_pytree_independently",
    "slice_array",
    "slice_pytree",
    "tuple_insert",
    "update_pytree",
    "TextBlock",
    "camelcase_to_snakecase",
    "colored",
    "format_datetime",
    "format_timedelta",
    "highlight_exception_message",
    "is_interactive_session",
    "outlined",
    "render_text_blocks",
    "show_error",
    "show_info",
    "show_warning",
    "snakecase_to_camelcase",
    "uncolored",
    "wrapped",
    "FrozenDict",
    "freeze_dict",
    "HashableArray",
    "hashable_array",
    "Optimizer",
    "Precision",
    "PrecisionConfig",
    "as_shape_dtype",
]

__all__ += [
    "ActivationType",
    "Batch",
    "CollateMode",
    "DiffusionBetaSchedule",
    "DiffusionLossFn",
    "DiffusionPredMode",
    "DTYPE",
    "EmbeddingKind",
    "LOG_ERROR_SUMMARY",
    "LOG_PING",
    "LOG_STATUS",
    "Metric",
    "NormType",
    "ODESolverType",
    "Output",
    "RawConfigType",
    "SigmaType",
    "StepKind",
]

import os
import shutil
from typing import TYPE_CHECKING

# Sets some useful XLA flags.
xla_flags: list[str] = []
if "XLA_FLAGS" in os.environ:
    xla_flags.append(os.environ["XLA_FLAGS"])

# If Nvidia GPU is detected (meaning, is `nvidia-smi` available?), disable
# Triton GEMM kernels. See https://github.com/NVIDIA/JAX-Toolbox
if shutil.which("nvidia-smi") is not None:
    xla_flags += [
        "--xla_gpu_enable_latency_hiding_scheduler=true",
        "--xla_gpu_enable_triton_gemm=false",
    ]
os.environ["XLA_FLAGS"] = " ".join(xla_flags)

# If this flag is set, eagerly imports the entire package (not recommended).
IMPORT_ALL = int(os.environ.get("XAX_IMPORT_ALL", "0")) != 0

del os, shutil, xla_flags

# This dictionary is auto-generated and shouldn't be modified by hand; instead,
# run the update script.
NAME_MAP: dict[str, str] = {
    "AttentionCache": "arch.attention",
    "CrossAttentionBlock": "arch.attention",
    "Fp8ScalesCache": "arch.attention",
    "RMSNorm": "arch.attention",
    "RotaryEmbedding": "arch.attention",
    "SelfAttentionBlock": "arch.attention",
    "SwiGLU": "arch.attention",
    "Transformer": "arch.attention",
    "TransformerBlock": "arch.attention",
    "TransformerBlockCache": "arch.attention",
    "TransformerCache": "arch.attention",
    "TransformerStack": "arch.attention",
    "apply_linear": "arch.attention",
    "can_use_cudnn_attention": "arch.attention",
    "BaseODESolver": "arch.diffusion",
    "ConsistencyModel": "arch.diffusion",
    "EulerODESolver": "arch.diffusion",
    "GaussianDiffusion": "arch.diffusion",
    "HeunODESolver": "arch.diffusion",
    "RK4ODESolver": "arch.diffusion",
    "cast_beta_schedule": "arch.diffusion",
    "cast_diffusion_loss_fn": "arch.diffusion",
    "cast_diffusion_pred_mode": "arch.diffusion",
    "cast_ode_solver_type": "arch.diffusion",
    "get_diffusion_beta_schedule": "arch.diffusion",
    "get_ode_solver": "arch.diffusion",
    "LLM": "arch.llm",
    "LLMConfig": "arch.llm",
    "LLMRepo": "arch.llm",
    "build_pretrained_model": "arch.llm",
    "chunked_cross_entropy_acc": "arch.llm",
    "chunked_cross_entropy_loss": "arch.llm",
    "hf_config_to_llm_config": "arch.llm",
    "llm_generate": "arch.llm",
    "llm_generate_jit": "arch.llm",
    "load_hf_config": "arch.llm",
    "load_hf_weights_into_llm": "arch.llm",
    "tie_embedding_and_head": "arch.llm",
    "BaseSSMBlock": "arch.ssm",
    "DiagSSMBlock": "arch.ssm",
    "SSM": "arch.ssm",
    "SSMBlock": "arch.ssm",
    "UNet": "arch.unet",
    "UserConfig": "core.conf",
    "field": "core.conf",
    "get_data_dir": "core.conf",
    "get_pretrained_models_dir": "core.conf",
    "get_run_dir": "core.conf",
    "load_user_config": "core.conf",
    "State": "core.state",
    "cast_step_kind": "core.state",
    "cast_activation_type": "nn.activation",
    "get_activation": "nn.activation",
    "Categorical": "nn.distributions",
    "MixtureOfGaussians": "nn.distributions",
    "Normal": "nn.distributions",
    "ProbabilityDistribution": "nn.distributions",
    "FourierEmbeddings": "nn.embeddings",
    "IdentityPositionalEmbeddings": "nn.embeddings",
    "LearnedPositionalEmbeddings": "nn.embeddings",
    "RotaryEmbeddings": "nn.embeddings",
    "SinusoidalEmbeddings": "nn.embeddings",
    "apply_rotary_embeddings": "nn.embeddings",
    "cast_embedding_kind": "nn.embeddings",
    "fourier_embeddings": "nn.embeddings",
    "get_positional_embeddings": "nn.embeddings",
    "get_rotary_embeddings": "nn.embeddings",
    "rotary_embeddings": "nn.embeddings",
    "cubic_bezier_interpolation": "nn.geom",
    "euler_to_quat": "nn.geom",
    "get_projected_gravity_vector_from_quat": "nn.geom",
    "normalize": "nn.geom",
    "quat_mul": "nn.geom",
    "quat_to_euler": "nn.geom",
    "quat_to_rotmat": "nn.geom",
    "quat_to_yaw": "nn.geom",
    "rotate_vector_by_quat": "nn.geom",
    "rotation6d_to_rotation_matrix": "nn.geom",
    "rotation_matrix_to_quat": "nn.geom",
    "rotation_matrix_to_rotation6d": "nn.geom",
    "LoRALinear": "nn.lora",
    "apply_lora_and_merge": "nn.lora",
    "extract_lora_weights": "nn.lora",
    "load_lora_weights": "nn.lora",
    "lora_filter_spec": "nn.lora",
    "loraize": "nn.lora",
    "loraize_by_path": "nn.lora",
    "loraize_linear": "nn.lora",
    "merge_lora": "nn.lora",
    "cast_euclidean_norm_type": "nn.metrics",
    "dynamic_time_warping": "nn.metrics",
    "get_euclidean_norm": "nn.metrics",
    "cast_norm_type": "nn.norm",
    "get_norm_1d": "nn.norm",
    "get_norm_2d": "nn.norm",
    "get_norm_3d": "nn.norm",
    "get_norm_linear": "nn.norm",
    "is_master": "nn.parallel",
    "BaseLauncher": "task.launchers.base",
    "CliLauncher": "task.launchers.cli",
    "MultiCpuLauncher": "task.launchers.multi_cpu",
    "MultiDeviceLauncher": "task.launchers.multi_device",
    "SingleDeviceLauncher": "task.launchers.single_device",
    "Distribution": "task.logger",
    "Histogram": "task.logger",
    "Image": "task.logger",
    "Images": "task.logger",
    "LabeledImages": "task.logger",
    "LogDistribution": "task.logger",
    "LogError": "task.logger",
    "LogErrorSummary": "task.logger",
    "LogGraph": "task.logger",
    "LogHistogram": "task.logger",
    "LogImage": "task.logger",
    "LogLine": "task.logger",
    "LogMesh": "task.logger",
    "LogPing": "task.logger",
    "LogScalar": "task.logger",
    "LogStatus": "task.logger",
    "LogVideo": "task.logger",
    "Logger": "task.logger",
    "LoggerImpl": "task.logger",
    "Mesh": "task.logger",
    "Scalar": "task.logger",
    "Tokens": "task.logger",
    "Video": "task.logger",
    "CallbackLogger": "task.loggers.callback",
    "JsonLogger": "task.loggers.json",
    "StateLogger": "task.loggers.state",
    "StdoutLogger": "task.loggers.stdout",
    "TensorboardLogger": "task.loggers.tensorboard",
    "load_ckpt": "task.mixins.checkpointing",
    "CPUStatsOptions": "task.mixins.cpu_stats",
    "DataloadersConfig": "task.mixins.data_loader",
    "DataloadersMixin": "task.mixins.data_loader",
    "GPUStatsOptions": "task.mixins.gpu_stats",
    "ParallelConfig": "task.mixins.parallel",
    "ParallelMixin": "task.mixins.parallel",
    "StepContext": "task.mixins.step_wrapper",
    "InitParams": "task.mixins.train",
    "Script": "task.script",
    "ScriptConfig": "task.script",
    "Config": "task.task",
    "SupervisedConfig": "task.task",
    "SupervisedTask": "task.task",
    "Task": "task.task",
    "collate": "utils.data.collate",
    "collate_non_null": "utils.data.collate",
    "breakpoint_if_nonfinite": "utils.debugging",
    "get_named_leaves": "utils.debugging",
    "log_if_nonfinite": "utils.debugging",
    "BaseFileDownloader": "utils.experiments",
    "ContextTimer": "utils.experiments",
    "CumulativeTimer": "utils.experiments",
    "DataDownloader": "utils.experiments",
    "IntervalTicker": "utils.experiments",
    "IterationTimer": "utils.experiments",
    "ModelDownloader": "utils.experiments",
    "NaNError": "utils.experiments",
    "StateTimer": "utils.experiments",
    "check_md5": "utils.experiments",
    "check_sha256": "utils.experiments",
    "cpu_count": "utils.experiments",
    "date_str": "utils.experiments",
    "diff_configs": "utils.experiments",
    "get_git_state": "utils.experiments",
    "get_random_port": "utils.experiments",
    "get_state_dict_prefix": "utils.experiments",
    "get_training_code": "utils.experiments",
    "save_config": "utils.experiments",
    "stage_environment": "utils.experiments",
    "to_markdown_table": "utils.experiments",
    "grad": "utils.jax",
    "jit": "utils.jax",
    "scan": "utils.jax",
    "to_numpy": "utils.jax",
    "to_scalar": "utils.jax",
    "vmap": "utils.jax",
    "save_jaxpr_dot": "utils.jaxpr",
    "ColoredFormatter": "utils.logging",
    "configure_logging": "utils.logging",
    "one_hot": "utils.numpy",
    "partial_flatten": "utils.numpy",
    "worker_chunk": "utils.numpy",
    "profile": "utils.profile",
    "compute_nan_ratio": "utils.pytree",
    "diff_pytree": "utils.pytree",
    "flatten_array": "utils.pytree",
    "flatten_pytree": "utils.pytree",
    "get_pytree_mapping": "utils.pytree",
    "get_pytree_param_count": "utils.pytree",
    "pytree_has_nans": "utils.pytree",
    "reshuffle_pytree": "utils.pytree",
    "reshuffle_pytree_along_dims": "utils.pytree",
    "reshuffle_pytree_independently": "utils.pytree",
    "slice_array": "utils.pytree",
    "slice_pytree": "utils.pytree",
    "tuple_insert": "utils.pytree",
    "update_pytree": "utils.pytree",
    "TextBlock": "utils.text",
    "camelcase_to_snakecase": "utils.text",
    "colored": "utils.text",
    "format_datetime": "utils.text",
    "format_timedelta": "utils.text",
    "highlight_exception_message": "utils.text",
    "is_interactive_session": "utils.text",
    "outlined": "utils.text",
    "render_text_blocks": "utils.text",
    "show_error": "utils.text",
    "show_info": "utils.text",
    "show_warning": "utils.text",
    "snakecase_to_camelcase": "utils.text",
    "uncolored": "utils.text",
    "wrapped": "utils.text",
    "FrozenDict": "utils.types.frozen_dict",
    "freeze_dict": "utils.types.frozen_dict",
    "HashableArray": "utils.types.hashable_array",
    "hashable_array": "utils.types.hashable_array",
    "Optimizer": "utils.types.training",
    "Precision": "utils.types.training",
    "PrecisionConfig": "utils.types.training",
    "as_shape_dtype": "utils.types.training",
}

# Need to manually set some values which can't be auto-generated.
NAME_MAP.update(
    {
        "ActivationType": "nn.activation",
        "Batch": "task.mixins.train",
        "CollateMode": "utils.data.collate",
        "DiffusionBetaSchedule": "arch.diffusion",
        "DiffusionLossFn": "arch.diffusion",
        "DiffusionPredMode": "arch.diffusion",
        "DTYPE": "nn.equinox",
        "EmbeddingKind": "nn.embeddings",
        "LOG_ERROR_SUMMARY": "utils.logging",
        "LOG_PING": "utils.logging",
        "LOG_STATUS": "utils.logging",
        "Metric": "task.logger",
        "NormType": "nn.metrics",
        "ODESolverType": "arch.diffusion",
        "Output": "task.mixins.output",
        "RawConfigType": "task.base",
        "SigmaType": "arch.diffusion",
        "StepKind": "core.state",
        "TransformerStack": "arch.attention",
    },
)


def __getattr__(name: str) -> object:
    if name not in NAME_MAP:
        raise AttributeError(f"{__name__} has no attribute {name}")

    module_name = f"xax.{NAME_MAP[name]}"
    module = __import__(module_name, fromlist=[name])
    return getattr(module, name)


if IMPORT_ALL or TYPE_CHECKING:
    from xax.arch.attention import (
        AttentionCache,
        CrossAttentionBlock,
        Fp8ScalesCache,
        RMSNorm,
        RotaryEmbedding,
        SelfAttentionBlock,
        SwiGLU,
        Transformer,
        TransformerBlock,
        TransformerBlockCache,
        TransformerCache,
        TransformerStack,
        apply_linear,
        can_use_cudnn_attention,
    )
    from xax.arch.diffusion import (
        BaseODESolver,
        ConsistencyModel,
        DiffusionBetaSchedule,
        DiffusionLossFn,
        DiffusionPredMode,
        EulerODESolver,
        GaussianDiffusion,
        HeunODESolver,
        RK4ODESolver,
        cast_beta_schedule,
        cast_diffusion_loss_fn,
        cast_diffusion_pred_mode,
        cast_ode_solver_type,
        get_diffusion_beta_schedule,
        get_ode_solver,
    )
    from xax.arch.llm import (
        LLM,
        LLMConfig,
        LLMRepo,
        build_pretrained_model,
        chunked_cross_entropy_acc,
        chunked_cross_entropy_loss,
        hf_config_to_llm_config,
        llm_generate,
        llm_generate_jit,
        load_hf_config,
        load_hf_weights_into_llm,
        tie_embedding_and_head,
    )
    from xax.arch.ssm import SSM, BaseSSMBlock, DiagSSMBlock, SSMBlock
    from xax.arch.unet import UNet
    from xax.core.conf import (
        UserConfig,
        field,
        get_data_dir,
        get_pretrained_models_dir,
        get_run_dir,
        load_user_config,
    )
    from xax.core.state import Batch, Output, State, StepKind, cast_step_kind
    from xax.nn.activation import ActivationType, cast_activation_type, get_activation
    from xax.nn.distributions import (
        Categorical,
        MixtureOfGaussians,
        Normal,
        ProbabilityDistribution,
    )
    from xax.nn.embeddings import (
        EmbeddingKind,
        FourierEmbeddings,
        IdentityPositionalEmbeddings,
        LearnedPositionalEmbeddings,
        RotaryEmbeddings,
        SinusoidalEmbeddings,
        apply_rotary_embeddings,
        cast_embedding_kind,
        fourier_embeddings,
        get_positional_embeddings,
        get_rotary_embeddings,
        rotary_embeddings,
    )
    from xax.nn.geom import (
        cubic_bezier_interpolation,
        euler_to_quat,
        get_projected_gravity_vector_from_quat,
        normalize,
        quat_mul,
        quat_to_euler,
        quat_to_rotmat,
        quat_to_yaw,
        rotate_vector_by_quat,
        rotation6d_to_rotation_matrix,
        rotation_matrix_to_quat,
        rotation_matrix_to_rotation6d,
    )
    from xax.nn.lora import (
        LoRALinear,
        apply_lora_and_merge,
        extract_lora_weights,
        load_lora_weights,
        lora_filter_spec,
        loraize,
        loraize_by_path,
        loraize_linear,
        merge_lora,
    )
    from xax.nn.metrics import NormType, cast_euclidean_norm_type, dynamic_time_warping, get_euclidean_norm
    from xax.nn.norm import NormType, cast_norm_type, get_norm_1d, get_norm_2d, get_norm_3d, get_norm_linear
    from xax.nn.parallel import is_master
    from xax.task.base import RawConfigType
    from xax.task.launchers.base import BaseLauncher
    from xax.task.launchers.cli import CliLauncher
    from xax.task.launchers.multi_cpu import MultiCpuLauncher
    from xax.task.launchers.multi_device import MultiDeviceLauncher
    from xax.task.launchers.single_device import SingleDeviceLauncher
    from xax.task.logger import (
        Distribution,
        Histogram,
        Image,
        Images,
        LabeledImages,
        LogDistribution,
        LogError,
        LogErrorSummary,
        Logger,
        LoggerImpl,
        LogGraph,
        LogHistogram,
        LogImage,
        LogLine,
        LogMesh,
        LogPing,
        LogScalar,
        LogStatus,
        LogVideo,
        Mesh,
        Metric,
        Scalar,
        Tokens,
        Video,
    )
    from xax.task.loggers.callback import CallbackLogger
    from xax.task.loggers.json import JsonLogger
    from xax.task.loggers.state import StateLogger
    from xax.task.loggers.stdout import StdoutLogger
    from xax.task.loggers.tensorboard import TensorboardLogger
    from xax.task.mixins.checkpointing import load_ckpt
    from xax.task.mixins.cpu_stats import CPUStatsOptions
    from xax.task.mixins.data_loader import DataloadersConfig, DataloadersMixin
    from xax.task.mixins.gpu_stats import GPUStatsOptions
    from xax.task.mixins.parallel import ParallelConfig, ParallelMixin
    from xax.task.mixins.step_wrapper import StepContext
    from xax.task.mixins.train import InitParams, Optimizer
    from xax.task.script import Script, ScriptConfig
    from xax.task.task import Config, SupervisedConfig, SupervisedTask, Task
    from xax.utils.data.collate import CollateMode, collate, collate_non_null
    from xax.utils.debugging import (
        breakpoint_if_nonfinite,
        get_named_leaves,
        log_if_nonfinite,
    )
    from xax.utils.experiments import (
        BaseFileDownloader,
        ContextTimer,
        CumulativeTimer,
        DataDownloader,
        IntervalTicker,
        IterationTimer,
        ModelDownloader,
        NaNError,
        StateTimer,
        check_md5,
        check_sha256,
        cpu_count,
        date_str,
        diff_configs,
        get_git_state,
        get_random_port,
        get_state_dict_prefix,
        get_training_code,
        save_config,
        stage_environment,
        to_markdown_table,
    )
    from xax.utils.jax import grad, jit, scan, to_numpy, to_scalar, vmap
    from xax.utils.jaxpr import save_jaxpr_dot
    from xax.utils.logging import (
        LOG_ERROR_SUMMARY,
        LOG_PING,
        LOG_STATUS,
        ColoredFormatter,
        configure_logging,
    )
    from xax.utils.numpy import one_hot, partial_flatten, worker_chunk
    from xax.utils.profile import profile
    from xax.utils.pytree import (
        compute_nan_ratio,
        diff_pytree,
        flatten_array,
        flatten_pytree,
        get_pytree_mapping,
        get_pytree_param_count,
        pytree_has_nans,
        reshuffle_pytree,
        reshuffle_pytree_along_dims,
        reshuffle_pytree_independently,
        slice_array,
        slice_pytree,
        tuple_insert,
        update_pytree,
    )
    from xax.utils.text import (
        TextBlock,
        camelcase_to_snakecase,
        colored,
        format_datetime,
        format_timedelta,
        highlight_exception_message,
        is_interactive_session,
        outlined,
        render_text_blocks,
        show_error,
        show_info,
        show_warning,
        snakecase_to_camelcase,
        uncolored,
        wrapped,
    )
    from xax.utils.types.frozen_dict import FrozenDict, freeze_dict
    from xax.utils.types.hashable_array import HashableArray, hashable_array
    from xax.utils.types.training import Optimizer, Precision, PrecisionConfig, as_shape_dtype

del TYPE_CHECKING, IMPORT_ALL
